#!/bin/sh

#pi@raspberrypi:~/configuration $ ls -lR .
#.:
#total 16
#-rwxr-xr-- 1 root root  959 Apr 23 19:28 ch
#drwxr-xr-x 4 root root 4096 Apr 23 18:24 etc
#drwxr-xr-x 2 pi   pi   4096 Apr 23 19:27 jupyter
#-rwxr-xr-x 1 pi   pi    628 Apr 23 19:30 switch-network-mode
#
#./etc:
#total 24
#-rw-rw-r-- 1 root netdev 1723 Apr 13  2018 dhcpcd.conf.homewifi
#-rw-rw-r-- 1 root netdev 1722 Apr 13  2018 dhcpcd.conf.router
#drwxr-xr-x 2 root root   4096 Apr 23 14:41 network
#-rwxrwxr-- 1 root root    550 Apr 23 16:07 rc.local
#-rw-r--r-- 1 root root    141 Apr 23 14:13 resolv.conf.head
#drwxr-xr-x 3 root root   4096 Apr 23 18:24 systemd
#
#./etc/network:
#total 8
#-rw-r--r-- 1 root root 291 Apr 23 14:41 interfaces.homewifi
#-rw-r--r-- 1 root root 425 Apr 13  2018 interfaces.router
#
#./etc/systemd:
#total 4
#drwxr-xr-x 2 root root 4096 Apr 23 19:18 system
#
#./etc/systemd/system:
#total 12
#-rw-r--r-- 1 root root 248 May 10 00:13 bluetooth_control.service
#-rw-r--r-- 1 root root 331 Apr 23 19:18 jupyter.service
#-rw-r--r-- 1 root root 310 Apr 23 16:08 mjpeg-streamer.service
#
#./jupyter:
#total 32
#-rw-r--r-- 1 pi pi 29376 Apr 23 19:27 jupyter_notebook_config.py
#-rw------- 1 pi pi   103 Apr 24 19:05 jupyter_notebook_config.json
chown -R root .
chgrp -R root .
chmod u+x ./update_thinkland_car_info
chmod u+x ./ch
chmod u+x ./switch-network-mode
chgrp netdev ./etc/dhcpcd.conf.homewifi
chgrp netdev ./etc/dhcpcd.conf.router
chmod 664 ./etc/dhcpcd.conf.homewifi
chmod 664 ./etc/dhcpcd.conf.router
chown -R pi ./jupyter
chgrp -R pi ./jupyter

