#!/bin/bash

teamviewer_id=`teamviewer info | grep 'TeamViewer ID'`
teamviewer_id=`[[ "${teamviewer_id}" =~ [[:blank:]]*([0-9]{2,}) ]] && echo ${BASH_REMATCH[1]}`
echo $teamviewer_id

internal_ip=`ifconfig | grep -v inet6 | grep inet | sed 's/.*inet *\([0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/'` 
internal_ip=`echo $internal_ip|sed -e 's/\t/,/g'|sed -e 's/ /,/g'`
echo $internal_ip

update_date=`date +%Y-%m-%dT%H:%M:%S -u`
echo $update_date

JSON_FMT='{"teamviewer_id":"%s", "internal_ip":"%s", "update_date":"%s"}'
data=`printf "$JSON_FMT" "$teamviewer_id" "$internal_ip" "$update_date"`
echo $data

curl -d "$(printf "$JSON_FMT" "$teamviewer_id" "$internal_ip" "$update_date")" -H "Content-Type: application/json" -X POST https://school.thinklandai.com/carconfig/`hostname`
echo
